# =========================================================================
# =========================================================================
# GT-IGU: ❌  |  TSI-Loss: ❌  |  STS+L_cons: ✅
# =========================================================================

mode: finetune
pretrained_path: null

use_consistency_loss: true
cons_weight: 0.1
cons_probability: 0.3
cons_warmup_epochs: 5
tsi_warmup_epochs: 0

dataset:
  common:
    NAME: ScanNet
    data_root: data/ScanNet
    voxel_size: 0.02

  train:
    split: train
    voxel_max: 32000
    loop: 6
    presample: False

  val:
    split: val
    presample: True
    voxel_max: null

  test:
    split: val
    presample: False
    voxel_max: null

model:
  NAME: BaseSeg

  encoder_args:
    NAME: PointNextEncoder
    blocks: [1, 2, 3, 2, 2]
    strides: [1, 4, 4, 4, 4]
    use_gt_igu: False
    sa_layers: 1
    sa_use_res: False
    width: 32
    in_channels: 7
    expansion: 4
    radius: 0.05
    nsample: 32
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'

  decoder_args:
    NAME: PointNextDecoder

  cls_args:
    NAME: SegHead
    global_feat: max
    num_classes: 20
    in_channels: null
    norm_args:
      norm: 'bn'

no_label: False
feature_keys: pos,x,heights
num_classes: 20
batch_size: 4
val_batch_size: 1

dataloader:
  num_workers: 6

datatransforms:
  train: [RandomRotateZ, RandomScale, ChromaticAutoContrast, RandomDropFeature, NumpyChromaticNormalize]
  val: [NumpyChromaticNormalize]
  test: [PointsToTensor, NumpyChromaticNormalize]
  vote: [ChromaticDropGPU]
  kwargs:
    color_drop: 0.2
    gravity_dim: 2
    rotate_dim: 2
    scale: [0.8, 1.2]
    mirror: [0.2, -1, -1]
    angle: 1
    color_mean: [0.46259782, 0.46253258, 0.46253258]
    color_std: [0.693565  , 0.6852543 , 0.68061745]

val_fn: validate
ignore_index: -1

epochs: 50
lr: 0.0005
min_lr: null

sched: multistep
decay_epochs: [35, 45]
decay_rate: 0.1
warmup_epochs: 2

cls_weighed_loss: False
criterion_args:
  NAME: CrossEntropy
  label_smoothing: 0.0
  ignore_index: -1

optimizer:
  NAME: 'adamw'
  weight_decay: 1.0e-4

grad_norm_clip: 10
use_voting: False

save_freq: -1
val_freq: 1

wandb:
  project: PointNeXt-Ablation-Finetune
  use_wandb: false
